export const columnsCarsProcessed = [
    { field: 'ID', headerName: 'ID', width: 0, hideable: true },
    { field: 'PROC_DT', headerName: 'Process Date', width: 150 },
    { field: 'RGN_NM_ENG', headerName: 'Region', width: 150 },
    { field: 'TRML_NM', headerName: 'Terminal', width: 150 },
    { field: 'EQP_INIT', headerName: 'Eqp Init', width: 150 },
    { field: 'EQP_NBR', headerName: 'Eqp Number', width: 150 },
    { field: 'Thru_train_identifier', headerName: 'Thru Train', width: 150 },
    { field: 'START_EVT_CD', headerName: 'Start Event Code', width: 150 },
    { field: 'START_EVST_CD', headerName: 'Start Event Station', width: 150 },
    { field: 'EVT_DT_FROM', headerName: 'Start Date', width: 150 },
    { field: 'EVT_TM_FROM', headerName: 'Start Time', width: 150 },
    { field: 'START_TRAIN_IDENTIFIER', headerName: 'Start Train', width: 150 },
    { field: 'EVT_DT_TO', headerName: 'End Date', width: 150 },
    { field: 'EVT_TM_TO', headerName: 'End Time', width: 150 },
    { field: 'END_EVT_CD', headerName: 'End Event Code', width: 150 },
    { field: 'END_EVST_CD', headerName: 'End Event Station', width: 150 },
    { field: 'End_Train_Identifier', headerName: 'End Train', width: 150 },
    { field: 'LOAD_MPTY_CD', headerName: 'Load/Empty Code', width: 150 },
    { field: 'DWL_TYPE_CD', headerName: 'Dwell Type Code', width: 150 },
    { field: 'CAR_GRP_CD', headerName: 'Car Group Code', width: 150 },
    { field: 'CAR_GRP_CLS_ENG', headerName: 'Car Group Class', width: 150 },
    { field: 'START_STN_333', headerName: 'Start Station (333)', width: 150 },
    { field: 'START_STN_PRST', headerName: 'Start Station Province', width: 150 },
    { field: 'END_STN_333', headerName: 'End Station (333)', width: 150 },
    { field: 'END_STN_PRST', headerName: 'End Station Province', width: 150 },
    { field: 'DWL_HR', headerName: 'Dwell Hours', width: 150 },
    { field: 'DWL_CAR_CNT', headerName: 'Dwell Car Count', width: 150 },
    { field: 'CATEGORY', headerName: 'Category', width: 150 },
    { field: 'EVT_DT', headerName: 'Event Date', width: 150 },
    { field: 'CAR_INIT', headerName: 'Car Initial', width: 150 },
    { field: 'CAR_NUMB', headerName: 'Car Number', width: 150 },
    { field: 'FirstOfCARR_ABBR_ON', headerName: 'Carrier Abbreviation', width: 150 },
    { field: 'FirstOfCUST_633_SHIP', headerName: 'Shipper (633)', width: 150 },
    { field: 'FirstOfOP_ORIG_333', headerName: 'Origin (333)', width: 150 },
    { field: 'FirstOfOP_ORIG_ST', headerName: 'Origin Province', width: 150 },
    { field: 'FirstOfOP_CITY_333', headerName: 'Origin City (333)', width: 150 },
    { field: 'FirstOfOP_ST', headerName: 'Origin Province', width: 150 },
    { field: 'FirstOfCUST_633_CNSG', headerName: 'Consignee (633)', width: 150 },
    { field: 'FirstOfOP_CUST_633', headerName: 'Operating Customer (633)', width: 150 },
    { field: 'FirstOfOP_RAJP', headerName: 'RAJP', width: 150 },
    { field: 'FirstOfYD_BLK', headerName: 'Yard Block', width: 150 },
    { field: 'FirstOfERT_CD', headerName: 'ERT Code', width: 150 },
    { field: 'FirstOfSFE_POOL_ID', headerName: 'SFE Pool ID', width: 150 },
    { field: 'FirstOfCMDTY_DES_ABBR', headerName: 'Commodity', width: 150 },
    { field: 'FirstOfTRN_BLK', headerName: 'Train Block', width: 150 },
    { field: 'FirstOfTRN_SEQ_NUMB', headerName: 'Train Sequence #', width: 150 },
    { field: 'FirstOfOS_CAR_LGTH', headerName: 'Car Length (OS)', width: 150 },
    { field: 'FirstOfGRS_TONS', headerName: 'Gross Tons', width: 150 },
    { field: 'Start_Trn_Short', headerName: 'Start Train (Short)', width: 150 },
    { field: 'Start_Trn_Day', headerName: 'Start Train Day', width: 150 },
    { field: 'End_Trn_Short', headerName: 'End Train (Short)', width: 150 },
    { field: 'End_Trn_Day', headerName: 'End Train Day', width: 150 },
];
