export const columnsCarsProcessed = [
    { field: 'ID', headerName: 'ID', width: 0, hideable: true },
    { field: 'PROC_DT', headerName: 'Process Date', width: 150 },
    { field: 'RGN_NM_ENG', headerName: 'Region', width: 150 },
    { field: 'TRML_NM', headerName: 'Terminal', width: 150 },
    { field: 'EQP_INIT', headerName: 'Car Init', width: 150 },
    { field: 'EQP_NBR', headerName: 'Car Number', width: 150 },
    { field: 'Thru_train_identifier', headerName: 'Thru Train', width: 150 },
    { field: 'START_EVT_CD', headerName: 'Start Event Code', width: 150 },
    { field: 'START_EVST_CD', headerName: 'Start Event Status', width: 150 },
    { field: 'EVT_DT_FROM', headerName: 'Start Date', width: 150 },
    { field: 'EVT_TM_FROM', headerName: 'Start Time', width: 150 },
    { field: 'START_TRAIN_IDENTIFIER', headerName: 'Start Train ID', width: 150 },
    { field: 'EVT_DT_TO', headerName: 'End Date', width: 150 },
    { field: 'EVT_TM_TO', headerName: 'End Time', width: 150 },
    { field: 'END_EVT_CD', headerName: 'End Event Code', width: 150 },
    { field: 'END_EVST_CD', headerName: 'End Event Status', width: 150 },
    { field: 'End_Train_Identifier', headerName: 'End Train ID', width: 150 },
    { field: 'LOAD_MPTY_CD', headerName: 'Load/Empty', width: 150 },
    { field: 'DWL_TYPE_CD', headerName: 'Dwell Type', width: 150 },
    { field: 'CAR_GRP_CD', headerName: 'Car Group', width: 150 },
    { field: 'CAR_GRP_CLS_ENG', headerName: 'Car Group Class', width: 150 },
    { field: 'START_STN_333', headerName: 'Start Station', width: 150 },
    { field: 'START_STN_PRST', headerName: 'Start Station Prov/State', width: 150 },
    { field: 'END_STN_333', headerName: 'End Station', width: 150 },
    { field: 'END_STN_PRST', headerName: 'End Station Prov/State', width: 150 },
    { field: 'DWL_HR', headerName: 'Dwell Hours', width: 150 },
    { field: 'DWL_CAR_CNT', headerName: 'Dwell Car Count', width: 150 },
    { field: 'CATEGORY', headerName: 'Category', width: 150 },
    { field: 'EVT_DT', headerName: 'Event Date', width: 150 },
    { field: 'CAR_INIT', headerName: 'Car Initial', width: 150 },
    { field: 'CAR_NUMB', headerName: 'Car Number', width: 150 },
    { field: 'FirstOfCARR_ABBR_ON', headerName: 'Carrier Abbreviation', width: 150 },
    { field: 'FirstOfCUST_633_SHIP', headerName: 'Shipper', width: 150 },
    { field: 'FirstOfOP_ORIG_333', headerName: 'Origin', width: 150 },
    { field: 'FirstOfOP_ORIG_ST', headerName: 'Origin Province', width: 150 },
    { field: 'FirstOfOP_CITY_333', headerName: 'Origin City', width: 150 },
    { field: 'FirstOfOP_ST', headerName: 'Origin Province', width: 150 },
    { field: 'FirstOfCUST_633_CNSG', headerName: 'Consignee', width: 150 },
    { field: 'FirstOfOP_CUST_633', headerName: 'Operating Customer', width: 150 },
    { field: 'FirstOfOP_RAJP', headerName: 'RAJP', width: 150 },
    { field: 'FirstOfYD_BLK', headerName: 'Yard Block', width: 150 },
    { field: 'FirstOfERT_CD', headerName: 'ERT Code', width: 150 },
    { field: 'FirstOfSFE_POOL_ID', headerName: 'SFE Pool ID', width: 150 },
    { field: 'FirstOfCMDTY_DES_ABBR', headerName: 'Commodity', width: 150 },
    { field: 'FirstOfTRN_BLK', headerName: 'Train Block', width: 150 },
    { field: 'FirstOfTRN_SEQ_NUMB', headerName: 'Train Sequence #', width: 150 },
    { field: 'FirstOfOS_CAR_LGTH', headerName: 'Car Length', width: 150 },
    { field: 'FirstOfGRS_TONS', headerName: 'Gross Tons', width: 150 },
    { field: 'Start_Trn_Short', headerName: 'Start Train (Short)', width: 150 },
    { field: 'Start_Trn_Day', headerName: 'Start Train Day', width: 150 },
    { field: 'End_Trn_Short', headerName: 'End Train (Short)', width: 150 },
    { field: 'End_Trn_Day', headerName: 'End Train Day', width: 150 },
    { field: 'WEEK', headerName: 'Week', width: 150 },
    { field: 'DOW', headerName: 'Day of Week', width: 150 },
    { field: 'YD_BLK3', headerName: 'Yard Block 3', width: 150 },
    { field: 'DAILY_AVG', headerName: 'Daily Average', width: 150 },
    { field: 'start_type_series', headerName: 'Start Type Series', width: 150 },
    { field: 'TD_SYM', headerName: 'TD SYM', width: 150 },
    { field: 'TA_SYM', headerName: 'TA SYM', width: 150 },
    { field: 'TRN_TRN', headerName: 'Train-Train', width: 150 },
    { field: 'START_EVENT_HOUR', headerName: 'Start Event Hour', width: 150 },
    { field: 'END_EVENT_HOUR', headerName: 'End Event Hour', width: 150 },
];
